"""35/36 main presentation plates, generated by generate_six_comparison_diagrams.

The original alternatives remain unchanged. These plates expose normal state
production and actual authority boundaries. They are documentation, not runtime
or sandbox implementations. SVG and editable draw.io share the same scene.
"""
from stage4_diagram_design import Plate, INK, MUTED, BLUE, GREEN, LINE

RED = '#B23C35'


class Presentation(Plate):
    def __init__(self, number, title, subtitle):
        super().__init__(f'choice{number}-structure', f'04-{number}', title, subtitle, height=1440)
        self.items = []
        self.serial = 0
        self.box(0, 0, 2560, 9, INK, 'none', 0)
        self.text(64, 26, 'VIA / ARCHITECTURE COMPARISON', 23, MUTED, bold=True)
        self.text(2496, 26, f'{number} / 설계 비교', 23, MUTED, 'right')
        self.text(64, 74, title, 48, bold=True)
        self.text(64, 142, subtitle, 29, MUTED)
        self.line([(64, 195), (2496, 195)], LINE, arrow=False)

    @staticmethod
    def text_geometry(i):
        size = 28
        leading = size * 1.25
        return i['y'] + (i['h']-len(i['name'])*leading)/2 - 2 + (8 if i['type']=='store' else 0), size, leading

    def svg(self):
        result = super().svg().replace('font-size="23"', 'font-size="28"')
        marker = f'<marker id="a{RED[1:]}" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse"><path d="M1 1L9 5L1 9" fill="none" stroke="{RED}" stroke-width="1.6"/></marker>'
        return result.replace('</defs>', marker+'</defs>')

    def drawio(self):
        return super().drawio().replace('fontSize=23;', 'fontSize=28;')

    def arrow(self, a, b, label='', at=None, sp='B', tp='T', via=(), color=INK, ret=False, sd=0, td=0, size=26):
        self.edge(a, b, sp=sp, tp=tp, via=list(via), color=color, ret=ret, sd=sd, td=td)
        if label:
            self.label(*at, label, color, size=size)

    def footer(self, note):
        self.line([(64, 1353), (2496, 1353)], LINE, arrow=False)
        legend = '실선: 요청/기록   점선: 반환/재구성   파랑: A   초록: B'
        if self.slug == 'choice36-structure':
            legend = '실선: 요청   점선: 반환   점선 외곽: process 경계   빨강: 우회 시도/거절'
        self.text(64, 1372, legend, 23, MUTED)
        self.text(2496, 1405, note, 23, MUTED, 'right')


def state_structure():
    p = Presentation(35, '대화와 업무 상태, 무엇을 원본으로 삼는가?',
                     '같은 정상 사용: 보고서 T1의 질문 Q7 “기간은?” → “상반기로 해줘” → 답변 확정과 업무 이어가기')
    p.text(64, 214, '공통 목적', 28, bold=True)
    p.text(260, 214, 'Q7 답변, T1 조건, 전송 준비를 일관되게 저장. Agent 접수와 사용자 실제 전달은 확인한 뒤 별도 기록.', 28)
    p.text(64, 262, '같은 해석과 검사', 27, bold=True)
    p.text(330, 262, '같은 Omni와 현재 권한/버전 검사. 어느 안도 기록만으로 외부 접수나 사용자 전달을 추정하지 않는다.', 27, MUTED)
    p.line([(1280, 325), (1280, 1330)], LINE, arrow=False)
    for s, dx, c, title, sub in [
        ('A', 0, BLUE, 'A  현재 상태가 원본', '상태 변경을 확정하고, 그 값을 읽어 계속 처리한다.'),
        ('B', 1250, GREEN, 'B  확정 사건이 원본', '사건을 확정하고, 같은 코드로 현재 상태를 계산한다.')]:
        p.text(80+dx, 326, title, 39, c, bold=True)
        p.text(80+dx, 382, sub, 28, c)
        p.component(s+'rc', 120+dx, 442, 450, 68, 'Request Controller')
        p.component(s+'tm', 740+dx, 442, 450, 68, 'Task Manager')
        p.component(s+'ss', 100+dx, 566, 1110, 469, 'State Store', c)
        p.node(s+'write', 145+dx, 650, 430, 68,
               'Record Update Module' if s=='A' else 'Journal Append Module', owner=s+'ss', color=c)
        p.arrow(s+'rc', s+'write', '1  '+('상태 변경 값' if s=='A' else '확정할 의미 사건'),
                (145+dx, 530), via=[(345+dx, 546),(360+dx,546)], color=c)
        p.arrow(s+'tm', s+'write', 'T1 조건과 전송 준비도 같은 확정 묶음',
                (690+dx, 530), sp='B', tp='R', via=[(965+dx,548),(1240+dx,548),(1240+dx,610),(605+dx,610),(605+dx,684)], color=c, size=24)
    p.node('Acurrent', 145, 820, 490, 103, '질문 / 업무 / 미완료 원장', kind='store', owner='Ass', color=BLUE)
    p.node('Aaudit', 780, 650, 385, 82, '감사 기록', kind='store', owner='Ass', color=BLUE)
    p.arrow('Awrite', 'Acurrent', '2  Q7=답변 완료 / T1=상반기\nc9=전송 대기', (155, 740), via=[(360,797),(390,797)], color=BLUE)
    p.arrow('Awrite', 'Aaudit', '같은 transaction', (582, 610), sp='R', tp='L', via=[(680,684),(680,691)], color=BLUE, size=25)
    p.label(740, 825, '권위 원본은 현재 기록\n감사 조회와 backup도 가능\n상태 변환 코드도 재사용 가능', BLUE, size=27)
    p.arrow('Acurrent', 'Arc', '3  정상 조회 / 재시작에도 현재 기록', (135, 981), sp='L', tp='L', via=[(80,871.5),(80,476)], color=BLUE, ret=True)

    p.node('Bjournal', 1395, 820, 430, 103, '확정 사건 원장', kind='store', owner='Bss', color=GREEN)
    p.node('Breducer', 2030, 650, 385, 68, 'Projection Module', owner='Bss', color=GREEN)
    p.node('Bview', 2030, 855, 385, 103, '현재 상태 / 사건 위치', kind='store', owner='Bss', color=GREEN)
    p.arrow('Bwrite', 'Bjournal', '2  답변 확정(Q7, 상반기)\n전송 준비(c9)', (1405, 740), color=GREEN)
    p.arrow('Bjournal', 'Breducer', '3  사건 적용', (1870, 718), sp='R', tp='L', via=[(1920,871.5),(1920,684)], color=GREEN)
    p.arrow('Breducer', 'Bview', '결정적 코드로 상태 계산', (2050, 786), color=GREEN)
    p.arrow('Bjournal', 'Breducer', '보존 사건으로 다시 계산', (1410, 966), sp='B', tp='B', via=[(1610,1012),(1970,1012),(1970,744),(2222.5,744)], color=GREEN, ret=True)
    p.arrow('Bview', 'Btm', '4  정상 조회', (2290, 1000), sp='R', tp='R', via=[(2480,906.5),(2480,476)], color=GREEN, ret=True, size=25)
    p.label(1995, 607, '사건 + 상태를 같은 transaction에 확정', GREEN, size=24)
    p.text(80, 1050, '반환 화살표는 대표 owner만 표시. 모든 owner가 자기 현재 상태를 조회한다.', 24, MUTED)
    p.text(1330, 1050, '재구성: 검증된 checkpoint로 단축 가능. 모델/외부 명령은 재실행 안 함.', 24, MUTED)

    p.line([(64, 1100), (2496, 1100)], LINE, arrow=False)
    p.text(80, 1118, '같은 사용자 결과', 28, bold=True)
    p.text(370, 1118, 'Agent Gateway가 저장된 명령을 전달 → 실제 접수 확인 → Response Manager가 상태를 안내하고 전달 사실 기록', 26)
    p.text(80, 1184, 'A의 선택 이유', 29, BLUE, bold=True)
    p.text(80, 1230, ['현재 운영과 필요한 감사 조회로 충분할 때', '직접 갱신 중심. 새 조회는 보존 정보와 변환에 의존'], 27, leading=42)
    p.text(1330, 1184, 'B의 선택 이유와 대가', 29, GREEN, bold=True)
    p.text(1330, 1230, ['재구성과 원인 검증, 조회 구조 변경을 반복 활용할 때', '대가: 사건의 장기 호환, 삭제와 재생 관리, 저장 공간'], 27, leading=42)
    p.footer('정상 정확도/속도 우열은 미측정. 감사 기록으로 충분하면 B의 추가 이익은 작다. / 미선정')
    return p


def isolation_structure():
    p = Presentation(36, '처리 코드가 검사를 우회할 때, 무엇이 접근을 막는가?',
                     '같은 정상 사용: 허용한 보고서 D7만 읽고 요약한다. 다른 파일이나 메일은 이번 요청 범위 밖이다.')
    p.text(64, 214, '공통 보호선', 28, bold=True)
    p.text(290, 214, '동의, 범위, 철회, 외부 제공 검사. 잘못된 모델 제안도 검사한다. 위험한 connector의 기존 격리는 양안 유지.', 27)
    p.text(64, 259, '추가로 비교할 위협', 27, bold=True)
    p.text(380, 259, '자료 조립/입력 구성 코드 자체의 침해. 모델의 오해와 구별하며 Broker, OS, 공유 모델 침해는 보호 범위 밖.', 27, MUTED)
    p.line([(1280, 322), (1280, 1330)], LINE, arrow=False)
    p.text(80, 323, 'A  권한을 가진 코드가 정책 준수', 38, BLUE, bold=True)
    p.text(1330, 323, 'B  처리 권한 제거 + 접근 중개', 38, GREEN, bold=True)
    p.box(80, 387, 1150, 635, '#F7FAFF', BLUE, 10, dashed=True, thick=2)
    p.text(100, 396, '신뢰 Core process / 처리 코드도 실제 자료 권한 보유', 26, BLUE, bold=True)
    for key,x,w,name in [('policy',120,330,'Policy Manager'),('rc',495,330,'Request Controller'),('state',870,330,'State Store')]:
        p.component('A'+key,x,446,w,66,name)
    p.component('Acm',120,583,465,367,'Context Manager')
    p.node('Aassemble',145,675,415,65,'자료 조립 Module',owner='Acm',color=BLUE)
    p.node('Aadapter',145,850,415,65,'자료 접근 Adapter',owner='Acm',color=BLUE)
    p.component('Ari',735,583,465,66,'Request Interpreter')
    p.component('Ama',735,850,465,66,'Model Access')
    p.arrow('Apolicy','Aassemble','허용 범위', (142,542), via=[(285,549),(110,549),(110,642),(352.5,642)],color=BLUE)
    p.arrow('Arc','Ari','1  입력 / 4  제안 검사', (765,535),via=[(660,545),(967.5,545)],color=BLUE)
    p.arrow('Ari','Arc','',sp='T',tp='B',sd=50,td=50,via=[(1017.5,565),(710,565)],color=BLUE,ret=True)
    p.arrow('Aassemble','Aadapter','2  범위 검사 후 읽기', (165,781),color=BLUE)
    p.arrow('Aadapter','Aassemble','',sp='T',tp='B',sd=60,td=60,color=BLUE,ret=True)
    p.arrow('Aassemble','Ari','자료/버전', (595,662),sp='R',tp='L',via=[(640,707.5),(640,616)],color=BLUE,ret=True)
    p.arrow('Ari','Aassemble','조회 요청', (595,729),sp='L',tp='R',sd=20,td=20,via=[(680,636),(680,727.5)],color=BLUE)
    p.arrow('Ari','Ama','3  추론 요청 / 결과 반환', (753,773),color=BLUE)
    p.arrow('Ama','Ari','',sp='T',tp='B',sd=55,td=55,color=BLUE,ret=True)
    p.node('Asource',145,1080,415,64,'OS 자료원',kind='external')
    p.node('Aomni',735,1080,465,64,'공유 Omni',kind='model')
    p.arrow('Aadapter','Asource','D7 읽기 / 내용 반환', (167,987),color=BLUE)
    p.arrow('Asource','Aadapter','',sp='T',tp='B',sd=65,td=65,color=BLUE,ret=True)
    p.arrow('Ama','Aomni','추론 / 반환', (975,1000))
    p.arrow('Aomni','Ama','',sp='T',tp='B',sd=65,td=65,ret=True)
    p.arrow('Aassemble','Asource','검사 우회: 보유 권한 범위 내 접근 위험', (110,1040),sp='L',tp='L',via=[(94,707.5),(94,1112)],color=RED,size=25)

    p.box(1330,513,485,440,'#F2FAF6',GREEN,10,dashed=True,thick=2)
    p.text(1350,528,'제한 process / 직접 자료 권한 없음',25,GREEN,bold=True)
    p.text(1350,561,'자료 조립/cache와 모델 입력 구성 코드',23,MUTED)
    p.box(1960,387,510,635,'#F7FAFF',INK,10,dashed=True,thick=2)
    p.text(1980,397,'신뢰 Core / 권한과 자격 보유',26,bold=True)
    for key,y,name in [('policy',446,'Policy Manager'),('rc',542,'Request Controller'),('state',632,'State Store'),('broker',742,'Data Access Broker'),('ma',937,'Model Access')]:
        p.component('B'+key,1980,y,470,66,name)
    p.component('Bri',1350,593,445,66,'Request Interpreter')
    p.component('Bcm',1350,839,445,66,'Context Manager')
    p.arrow('Brc','Bri','1  입력 / 4  제안 검증', (1360,465),sp='L',tp='R',td=-20,via=[(1880,575),(1880,606)],color=GREEN,size=24)
    p.arrow('Bri','Brc','',sp='R',tp='L',sd=-5,td=20,via=[(1855,621),(1855,595)],color=GREEN,ret=True)
    p.arrow('Bri','Bcm','필요한 자료 / 반환', (1365,753),sd=-40,td=-40,color=GREEN)
    p.arrow('Bcm','Bri','',sp='T',tp='B',sd=40,td=40,color=GREEN,ret=True)
    p.arrow('Bcm','Bbroker','2  handle로 읽기 / 자료 반환', (1355,919),sp='R',tp='L',sd=-10,td=25,via=[(1850,862),(1850,800)],color=GREEN,size=24)
    p.arrow('Bbroker','Bcm','',sp='L',tp='R',sd=32,td=10,via=[(1870,807),(1870,882)],color=GREEN,ret=True)
    p.arrow('Bri','Bbroker','3  모델 job / 결과', (1380,684),sp='R',tp='L',sd=15,td=-15,via=[(1900,641),(1900,760)],color=GREEN,size=25)
    p.arrow('Bbroker','Bri','요청별 handle도 Broker 발급',at=(1375,717),sp='L',tp='R',sd=5,td=25,via=[(1925,780),(1925,651)],color=GREEN,ret=True,size=24)
    p.arrow('Bpolicy','Bbroker','정책/현재 요청 확인', (2070,702),sp='R',tp='R',via=[(2490,479),(2490,775)],color=GREEN,size=24)
    p.arrow('Brc','Bbroker','',sp='R',tp='R',sd=15,td=15,via=[(2510,590),(2510,790)],color=GREEN)
    p.arrow('Bbroker','Bma','허용한 모델 호출', (1995,862),color=GREEN)
    p.arrow('Bma','Bbroker','',sp='T',tp='B',sd=65,td=65,color=GREEN,ret=True)
    p.node('Bos',1350,985,445,64,'OS 접근 제어',kind='external')
    p.node('Bsource',1350,1080,445,64,'OS 자료원',kind='external')
    p.node('Bomni',1980,1080,470,64,'공유 Omni',kind='model')
    p.arrow('Bcm','Bos','직접 파일/망 우회 → OS 거절', (1345,964),sp='L',tp='L',via=[(1320,872),(1320,1017)],color=RED,size=25)
    p.arrow('Bbroker','Bsource','D7 읽기 / 내용 반환', (1855,1036),sp='L',tp='R',sd=30,via=[(1950,805),(1950,1112)],color=GREEN,size=24)
    p.arrow('Bsource','Bbroker','',sp='R',tp='L',sd=20,td=32,via=[(1940,1132),(1940,807)],color=GREEN,ret=True)
    p.arrow('Bma','Bomni','추론 / 반환', (2250,1029))
    p.arrow('Bomni','Bma','',sp='T',tp='B',sd=65,td=65,ret=True)
    p.label(1995,812,'범위 밖 요청은 Broker 거절',RED,size=24)

    p.line([(64,1166),(2496,1166)],LINE,arrow=False)
    p.text(80,1180,'공통 반환: Request Controller가 현재 검사 → Response Manager / Interaction Manager가 요약 전달. 외부 인계는 Agent Gateway 검사.',25)
    p.text(80,1228,['A: 공유 호출과 기존 선택적 격리 활용', '잔여 위험을 수용할 수 있는 보호 수준일 때 후보'],27,BLUE,leading=42)
    p.text(1330,1228,['B: 범위 밖 접근 제한 ↔ IPC/권한 수명/OS 대응 비용', '이 처리 코드의 침해 격리가 필수이면 A는 부적격'],27,GREEN,leading=42)
    p.footer('B는 자료 조립/입력 구성 코드의 우회를 제한. OS 강제, 지연과 자원 효과는 검증 전. / 미선정')
    return p
